services:
  codeclash.api:
    image: ${DOCKER_REGISTRY-}codeclashapi
    build:
      context: .
      dockerfile: src/CodeClash.API/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081

    depends_on:
      - codeclash-db
      - codeclash-cache
      - codeclash-seq
      - elasticsearch

  codeclash-seq:
    image: datalust/seq:latest
    container_name: CodeClash.Seq
    environment:
     - ACCEPT_EULA=Y
     - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
     - 5341:80

  codeclash-db:
    image: postgres:17
    container_name: CodeClash.Db
    environment:
      POSTGRES_DB: codeclash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  codeclash-cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


      
  elasticsearch:
    container_name: elasticSearch
    image: elasticsearch:8.15.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false


  kibana:
    container_name: kibana
    image: kibana:8.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  elasticsearch-data:       