// <auto-generated />
using System;
using CodeClash.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeClash.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317001551_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeClash.Domain.Models.Blogs.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_blogs");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_blogs_creator_id");

                    b.ToTable("blogs", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Blogs.BlogImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_id");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.HasKey("Id")
                        .HasName("pk_tutorial_images");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_tutorial_images_blog_id");

                    b.ToTable("tutorial_images", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_id");

                    b.Property<string>("Contest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contest");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comment_author_id");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_comment_blog_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Contests.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BlogId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SetterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setter_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_contests");

                    b.HasIndex("BlogId")
                        .IsUnique()
                        .HasDatabaseName("ix_contests_blog_id");

                    b.HasIndex("SetterId")
                        .HasDatabaseName("ix_contests_setter_id");

                    b.ToTable("contests", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Contests.UserContest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<short>("RankChange")
                        .HasColumnType("smallint")
                        .HasColumnName("rank_change");

                    b.HasKey("UserId", "ContestId")
                        .HasName("pk_registers");

                    b.HasIndex("ContestId")
                        .HasDatabaseName("ix_registers_contest_id");

                    b.ToTable("registers", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank_name");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BlogId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<int>("ContestPoints")
                        .HasColumnType("integer")
                        .HasColumnName("contest_points");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<decimal>("MemoryLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("memory_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("RunTimeLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("run_time_limit");

                    b.Property<string>("SetterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setter_id");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_problems_blog_id");

                    b.HasIndex("ContestId")
                        .HasDatabaseName("ix_problems_contest_id");

                    b.HasIndex("SetterId")
                        .HasDatabaseName("ix_problems_setter_id");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.ProblemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_images");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_images_problem_id");

                    b.ToTable("problem_images", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.ProblemTopic", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("ProblemId", "TopicId")
                        .HasName("pk_problem_topics");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_problem_topics_topic_id");

                    b.ToTable("problem_topics", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Submits.Submit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid?>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.Property<decimal?>("SubmitMemory")
                        .HasColumnType("numeric")
                        .HasColumnName("submit_memory");

                    b.Property<decimal?>("SubmitTime")
                        .HasColumnType("numeric")
                        .HasColumnName("submit_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_submits");

                    b.HasIndex("ContestId")
                        .HasDatabaseName("ix_submits_contest_id");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_submits_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_submits_user_id");

                    b.ToTable("submits", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.TestCases.Testcase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_testcases");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_testcases_problem_id");

                    b.ToTable("testcases", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Topics.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Blogs.Blog", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "BlogCreator")
                        .WithMany("Blogs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blogs_application_user_creator_id");

                    b.Navigation("BlogCreator");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Blogs.BlogImage", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Blogs.Blog", "Blog")
                        .WithMany("Images")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorial_images_blogs_blog_id");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Comments.Comment", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_application_user_author_id");

                    b.HasOne("CodeClash.Domain.Models.Blogs.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_blogs_blog_id");

                    b.Navigation("Author");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Contests.Contest", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Blogs.Blog", "Blog")
                        .WithOne("Contest")
                        .HasForeignKey("CodeClash.Domain.Models.Contests.Contest", "BlogId")
                        .HasConstraintName("fk_contests_blogs_blog_id");

                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "ProblemSetter")
                        .WithMany("Contests")
                        .HasForeignKey("SetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contests_application_user_setter_id");

                    b.Navigation("Blog");

                    b.Navigation("ProblemSetter");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Contests.UserContest", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Contests.Contest", "Contest")
                        .WithMany("Registrations")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registers_contests_contest_id");

                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registers_application_user_user_id");

                    b.Navigation("Contest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.Problem", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Blogs.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .HasConstraintName("fk_problems_blogs_blog_id");

                    b.HasOne("CodeClash.Domain.Models.Contests.Contest", "Contest")
                        .WithMany("Problems")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problems_contests_contest_id");

                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "ProblemSetter")
                        .WithMany("Problems")
                        .HasForeignKey("SetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problems_application_user_setter_id");

                    b.Navigation("Blog");

                    b.Navigation("Contest");

                    b.Navigation("ProblemSetter");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.ProblemImage", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Problems.Problem", "Problem")
                        .WithMany("Images")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_images_problems_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.ProblemTopic", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Problems.Problem", "Problem")
                        .WithMany("ProblemTopics")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_topics_problems_problem_id");

                    b.HasOne("CodeClash.Domain.Models.Topics.Topic", "Topic")
                        .WithMany("ProblemTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_topics_topics_topic_id");

                    b.Navigation("Problem");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Submits.Submit", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Contests.Contest", "Contest")
                        .WithMany("Submissions")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_submits_contests_contest_id");

                    b.HasOne("CodeClash.Domain.Models.Problems.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submits_problems_problem_id");

                    b.HasOne("CodeClash.Domain.Models.Identity.ApplicationUser", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submits_application_user_user_id");

                    b.Navigation("Contest");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.TestCases.Testcase", b =>
                {
                    b.HasOne("CodeClash.Domain.Models.Problems.Problem", "Problem")
                        .WithMany("Testcases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_testcases_problems_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Blogs.Blog", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contest")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Contests.Contest", b =>
                {
                    b.Navigation("Problems");

                    b.Navigation("Registrations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Comments");

                    b.Navigation("Contests");

                    b.Navigation("Problems");

                    b.Navigation("Registrations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Problems.Problem", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProblemTopics");

                    b.Navigation("Submissions");

                    b.Navigation("Testcases");
                });

            modelBuilder.Entity("CodeClash.Domain.Models.Topics.Topic", b =>
                {
                    b.Navigation("ProblemTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
