name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  DOTNET_VERSION: "9.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore CodeClash.sln --ignore-failed-sources
        env:
          DOTNET_NOLOGO: true

      - name: Build
        run: >
          dotnet build CodeClash.sln
          --configuration Release
          --no-restore
          -p:TreatWarningsAsErrors=true
          -p:EnforceCodeStyleInBuild=true
          /p:DockerComposeProjectsPath=
        env:
          DOTNET_NOLOGO: true

      - name: Test
        run: >
          dotnet test CodeClash.sln
          --configuration Release
          --no-restore
          --no-build
          --verbosity normal
          --logger "trx;LogFileName=test-results.trx"
        env:
          DOTNET_NOLOGO: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"

      - name: Publish API
        run: >
          dotnet publish src/CodeClash.API/CodeClash.API.csproj
          --configuration Release
          --no-restore
          --no-build
          --output ./publish
        env:
          DOTNET_NOLOGO: true
